export default [
    {
        image: "../images/productimage1.svg",
        title: "PORK LOIN",
        subtitle: "SUBTITLE",
        note: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        kg: 5.5,
        price: 10.99,
    },
    {
        image: "../images/productimage2.svg",
        title: "PORK LOIN",
        subtitle: "SUBTITLE",
        note: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        kg: 5.5,
        price: 10.99,
    },
    {
        image: "../images/productimage3.svg",
        title: "PORK LOIN",
        subtitle: "SUBTITLE",
        note: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        kg: 5.5,
        price: 10.99,
    },
    {
        image: "../images/productimage4.svg",
        title: "PORK LOIN",
        subtitle: "SUBTITLE",
        note: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        kg: 5.5,
        price: 10.99,
    },
    {
        image: "../images/productimage5.svg",
        title: "PORK LOIN",
        subtitle: "SUBTITLE",
        note: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        kg: 5.5,
        price: 10.99,
    },
    {
        image: "../images/productimage6.svg",
        title: "PORK LOIN",
        subtitle: "SUBTITLE",
        note: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        kg: 5.5,
        price: 10.99,
    },
]